name: 'cml#1030'
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: dacbd/custom-cml-tpi@main
        with:
          cml: runner-no-special-cases
      - uses: actions/checkout@v3
        with:
          path: main
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/200200923017/locations/global/workloadIdentityPools/gh-actions-pool/providers/github-actions'
          service_account: 'cml-runner@cml-pulse.iam.gserviceaccount.com'
      - name: Run CML Branch
        run: |
          pushd main
          ../cml/bin/cml.js runner \
            --single \
            --cml-version=github:iterative/cml#runner-no-special-cases \
            --labels=test \
            --token=${{ secrets.DACBD_PAT }} \
            --cloud=gcp \
            --cloud-region=us-west \
            --cloud-type=c2-standard-4 \
            --cloud-startup-script=$(echo 'echo "$(curl https://github.com/'"$GITHUB_ACTOR"'.keys)" >> /home/ubuntu/.ssh/authorized_keys' | base64 -w 0)
  test:
    needs: [setup]
    runs-on: [self-hosted, test]
    steps:           
      - uses: actions/checkout@v3
      - run: |
          which cml
          cml --version
  as-env:
    runs-on: ubuntu-latest
    steps:
      - uses: dacbd/custom-cml-tpi@main
        with:
          cml: runner-no-special-cases
      - uses: actions/checkout@v3
        with:
          path: main
      - name: run cml
        env:
          GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.GCP_CML_RUNNER_KEY }}
        run: |
          pushd main
          ../cml/bin/cml.js runner \
            --single \
            --labels=test-as-env \
            --token=${{ secrets.DACBD_PAT }} \
            --cloud=gcp \
            --cloud-region=us-west \
            --cloud-type=e2-highcpu-2 \
            --cloud-startup-script=ZWNobyAiZWNkc2Etc2hhMi1uaXN0cDM4NCBBQUFBRTJWalpITmhMWE5vWVRJdGJtbHpkSEF6T0RRQUFBQUlibWx6ZEhBek9EUUFBQUJoQkRZZDNzc2E2TDE1alFDNWJja0oydmlXbEExdEJ5Z3hlV295M3MwUzE0WkhNeFVNZnA3dTJ5cWZpY3BITzViK3BqZ2c3THorODBJYncxNTd3YVRaUE0reGJGMi9LR3FTN2FZVjBML1I4VmJXalZFcHp4WkVlb3hTQ3dGQTF0SFdVZz09IGNhcmRubzowMDA2MTE4OTU1NzUiID4+IC9ob21lL3VidW50dS8uc3NoL2F1dGhvcml6ZWRfa2V5cwo=
  test-as-env:
    needs: [as-env]
    runs-on: [self-hosted, test-as-env]
    steps:           
      - uses: actions/checkout@v2
      - run: |
          which cml
          cml --version
  standard:
    runs-on: ubuntu-latest
    steps:
      - uses: dacbd/custom-cml-tpi@main
        with:
          cml: runner-no-special-cases
      - uses: actions/checkout@v3
        with:
          path: main
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CML_RUNNER_KEY }}
      - run: |
          pushd main
          ../cml/bin/cml.js runner \
            --single \
            --labels=test-standard \
            --token=${{ secrets.DACBD_PAT }} \
            --cloud=gcp \
            --cloud-region=us-west \
            --cloud-type=e2-highcpu-2 \
            --cloud-startup-script=ZWNobyAiZWNkc2Etc2hhMi1uaXN0cDM4NCBBQUFBRTJWalpITmhMWE5vWVRJdGJtbHpkSEF6T0RRQUFBQUlibWx6ZEhBek9EUUFBQUJoQkRZZDNzc2E2TDE1alFDNWJja0oydmlXbEExdEJ5Z3hlV295M3MwUzE0WkhNeFVNZnA3dTJ5cWZpY3BITzViK3BqZ2c3THorODBJYncxNTd3YVRaUE0reGJGMi9LR3FTN2FZVjBML1I4VmJXalZFcHp4WkVlb3hTQ3dGQTF0SFdVZz09IGNhcmRubzowMDA2MTE4OTU1NzUiID4+IC9ob21lL3VidW50dS8uc3NoL2F1dGhvcml6ZWRfa2V5cwo=
  test-standard:
    needs: [standard]
    runs-on: [self-hosted, test-standard]
    steps:           
      - uses: actions/checkout@v2
      - run: |
          which cml
          cml --version
  oidc:
    runs-on: ubuntu-latest
    steps:
      - uses: dacbd/custom-cml-tpi@main
        with:
          cml: runner-no-special-cases
      - uses: actions/checkout@v3
        with:
          path: main
      - uses: dacbd/custom-cml-tpi@main
        with:
          cml: runner-no-special-cases
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/200200923017/locations/global/workloadIdentityPools/gh-actions-pool/providers/github-actions'
          service_account: 'cml-runner@cml-pulse.iam.gserviceaccount.com'
      - run: |
          pushd main
          ../cml/bin/cml.js runner \
            --single \
            --labels=test-oidc \
            --token=${{ secrets.DACBD_PAT }} \
            --cloud=gcp \
            --cloud-region=us-west \
            --cloud-type=e2-highcpu-2 \
            --cloud-startup-script=ZWNobyAiZWNkc2Etc2hhMi1uaXN0cDM4NCBBQUFBRTJWalpITmhMWE5vWVRJdGJtbHpkSEF6T0RRQUFBQUlibWx6ZEhBek9EUUFBQUJoQkRZZDNzc2E2TDE1alFDNWJja0oydmlXbEExdEJ5Z3hlV295M3MwUzE0WkhNeFVNZnA3dTJ5cWZpY3BITzViK3BqZ2c3THorODBJYncxNTd3YVRaUE0reGJGMi9LR3FTN2FZVjBML1I4VmJXalZFcHp4WkVlb3hTQ3dGQTF0SFdVZz09IGNhcmRubzowMDA2MTE4OTU1NzUiID4+IC9ob21lL3VidW50dS8uc3NoL2F1dGhvcml6ZWRfa2V5cwo=
  test-oidc:
    needs: [oidc]
    runs-on: [self-hosted, test-oidc]
    steps:           
      - uses: actions/checkout@v2
      - run: |
          which cml
          cml --version

  aws-oidc:
    runs-on: ubuntu-latest
    steps:
      - uses: dacbd/custom-cml-tpi@main
        with:
          cml: runner-no-special-cases
      - uses: actions/checkout@v3
        with:
          path: main
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::548501963152:role/cml_pulse_runner
          aws-region: us-west-2
      - name: deploy runner
        run: |
          pushd main
          ../cml/bin/cml.js runner \
            --single \
            --labels=basic_aws \
            --token=${{ secrets.DACBD_PAT }} \
            --cloud=aws \
            --cloud-region=us-west-2 \
            --cloud-type=t3.small
  basic_aws_test:
    needs: [aws-oidc]
    runs-on: [self-hosted, basic_aws]
    steps:           
      - uses: actions/checkout@v3
      - run: |
          which cml
          cml --version

  target-subnet: # make a pivot test (no public ips)
    needs: [basic_aws_test]
    runs-on: ubuntu-latest
    steps:
      - uses: dacbd/custom-cml-tpi@main
        with:
          cml: runner-no-special-cases
      - uses: actions/checkout@v3
        with:
          path: main
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::548501963152:role/cml_pulse_runner
          aws-region: us-west-2
      - name: deploy runner
        run: |
          pushd main
          ../cml/bin/cml.js runner \
            --single \
            --labels=target_subnet \
            --token=${{ secrets.DACBD_PAT }} \
            --cloud=aws \
            --cloud-region=us-west-2 \
            --cloud-type=t3.small \
            --cloud-aws-security-group=cml-target-rule \
            --cloud-aws-subnet-id=subnet-071ac872d5f008add
  target-subnet-test:
    needs: [target-subnet]
    runs-on: [self-hosted, target_subnet]
    steps:
      - uses: actions/checkout@v3
      - run: |
          which cml
          cml --version

  target-vpc:
    needs: [basic_aws_test]
    runs-on: ubuntu-latest
    steps:
      - uses: dacbd/custom-cml-tpi@main
        with:
          cml: runner-no-special-cases
      - uses: actions/checkout@v3
        with:
          path: main
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::548501963152:role/cml_pulse_runner
          aws-region: us-west-2
      - name: deploy runner
        run: |
          pushd main
          ../cml/bin/cml.js runner \
            --single \
            --labels=target_vpc \
            --token=${{ secrets.DACBD_PAT }} \
            --cloud=aws \
            --cloud-region=us-west-2 \
            --cloud-type=t3.small \
            --cloud-aws-security-group=cml-target-rule
  target-vpc-test:
    needs: [target-vpc]
    runs-on: [self-hosted, target_vpc]
    steps:
      - uses: actions/checkout@v3
      - run: |
          which cml
          cml --version