name: GCP manual Nvidia Driver
on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
      - name: run cml
        env:
          GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.TEMP_KEY }}
          REPO_TOKEN: ${{ secrets.DACBD_PAT }}
        run: |
          cml runner \
            --cloud=gcp \
            --cloud-region=us-central1-a \
            --cloud-type=n1-standard-4+nvidia-tesla-t4*1 \
            --cloud-hdd-size=100 \
            --labels=cml-runner \
            --idle-timeout=3000 \
            --single

  test:
    needs: [deploy]
    runs-on: [cml-runner]
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-dvc@v1
      - run: sudo systemd-run --pipe --service-type=exec bash -c 'curl https://gist.githubusercontent.com/dacbd/c527d1a214f7118e6d66e52a6abb4c4f/raw/db3cba14dcc4a23fb1b7c7a115563942d4164aaf/nvidia-src-setup.sh | bash'
      - run: |
          dvc doctor
          nvidia-smi
        
