name: temp
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # tools
      - uses: actions/checkout@v3
        with:
          repository: iterative/cml
          path: cml
      - uses: actions/checkout@v3
        with:
          repository: iterative/terraform-provider-iterative
          ref: gcp-oidc-terminate
          path: terraform-provider-iterative
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'

      - name: Hack together
        run: |
          echo "hack test together"
          pushd terraform-provider-iterative
          make build
          make install
          popd && pushd cml
          npm install
          sed -i "s/default: '>= 0.9.10'/default: ''/g" bin/cml/runner.js
          sed -i 's/source = "iterative\/iterative"/source = "github.com\/iterative\/iterative"/g' src/terraform.js
          sed -i 's/return template;/console.log(template);return template;/g' src/terraform.js
          popd

      - uses: actions/checkout@v3
        with:
          path: main
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/200200923017/locations/global/workloadIdentityPools/gh-actions-pool/providers/github-actions'
          service_account: 'cml-runner@cml-pulse.iam.gserviceaccount.com'
      - name: Run hacked CML
        run: |
          pushd main
          ../cml/bin/cml.js runner \
            --cml-version=github:iterative/cml#gcp-oidc-logging \
            --labels=term-test \
            --token=${{ secrets.DACBD_PAT }} \
            --cloud=gcp \
            --cloud-region=us-west \
            --cloud-type=c2-standard-4 \
            --cloud-startup-script=ZWNobyAiZWNkc2Etc2hhMi1uaXN0cDM4NCBBQUFBRTJWalpITmhMWE5vWVRJdGJtbHpkSEF6T0RRQUFBQUlibWx6ZEhBek9EUUFBQUJoQkRZZDNzc2E2TDE1alFDNWJja0oydmlXbEExdEJ5Z3hlV295M3MwUzE0WkhNeFVNZnA3dTJ5cWZpY3BITzViK3BqZ2c3THorODBJYncxNTd3YVRaUE0reGJGMi9LR3FTN2FZVjBML1I4VmJXalZFcHp4WkVlb3hTQ3dGQTF0SFdVZz09IGNhcmRubzowMDA2MTE4OTU1NzUiID4+IC9ob21lL3VidW50dS8uc3NoL2F1dGhvcml6ZWRfa2V5cwo=
  test:
    needs: [setup]
    runs-on: [self-hosted, term-test]
    steps:           
      - uses: actions/checkout@v2
      - run: |
          which cml
          cml --version
