name: temp
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: dacbd/custom-cml-tpi@main
        with:
          cml: master
          tpi: gcp-oidc-terminate
      - uses: actions/checkout@v3
        with:
          path: main
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/200200923017/locations/global/workloadIdentityPools/gh-actions-pool/providers/github-actions'
          service_account: 'cml-runner@cml-pulse.iam.gserviceaccount.com'
      - name: Run hacked CML
        run: |
          pushd main
          ../cml/bin/cml.js runner \
            --cml-version=github:iterative/cml#gcp-oidc-logging \
            --labels=term-test \
            --token=${{ secrets.DACBD_PAT }} \
            --cloud=gcp \
            --cloud-region=us-west \
            --cloud-type=c2-standard-4 \
            --cloud-startup-script=$(echo 'echo "$(curl https://github.com/'"$GITHUB_ACTOR"'.keys)" >> /home/ubuntu/.ssh/authorized_keys' | base64 -w 0)
  test:
    needs: [setup]
    runs-on: [self-hosted, term-test]
    steps:           
      - uses: actions/checkout@v2
      - run: |
          which cml
          cml --version
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'
      - name: intercept tpi
        run: |
          cd ../../
          pwd
          ls -hal
          #exit
          #pushd ~/
          sed -i 's/iterative = { source = "iterative\/iterative", version = ">= 0.9.10" }/iterative = { source = "github.com\/iterative\/iterative" }/g' main.tf
          sed -i 's/registry.terraform.io/github.com/g' terraform.tfstate
          rm -rf .terraform/
          rm .terraform.lock.hcl
          git clone https://github.com/iterative/terraform-provider-iterative.git
          pushd terraform-provider-iterative
          git checkout gcp-oidc-terminate
          make build
          make install
          popd
          terraform init
