name: gcpcc test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #- name: 'Authenticate to Google Cloud'
      #  uses: 'google-github-actions/auth@v0'
      #  with:
      #    credentials_json: ${{ secrets.GCP_CML_RUNNER_KEY }}
      - uses: dacbd/gcpcc@actionify
        id: gcpcc
        env:
          GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.GCP_CML_RUNNER_KEY }}
      - run: echo "${{ steps.gcpcc.outputs.total }}"