name: OIDC Cheat Test
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: dacbd/gcpcc
          path: test
          ref: dev
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/200200923017/locations/global/workloadIdentityPools/gh-actions-pool/providers/github-actions'
          service_account: 'cml-runner@cml-pulse.iam.gserviceaccount.com'
      #- uses: iterative/setup-cml@v1
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'
      - run: | 
          pushd test
          go run main.go